questions_data = [
	{
    "Target_ID": 39,
    "Target Label": "Target Label",
    "Target Subdomain": "Target Subdomain",
    "Question_ID": 1,
    "Question": "Wat doet een **kracht**, $F$",
    "Explanation": "Om dit op te lossen, doorloop je de volgende stappen:\n1. Bereken de vertraging van de auto\n2. Gebruik de vertraging om de remtijd te berekenen\n3. Gebruik de remtijd en de gemiddelde snelheid om de remweg te berekenen\n\n**1. Bereken $a_{\\textrm{rem}}$**\n Uit de Tweede wet van Newton ($F_{res}= m\\cdot a$) volgt: $$a = \\frac{F_{res}}{m}=\\frac{4000 \\textrm{ N}}{1200 \\textrm{ kg}}=3.33 \\textrm{ m/s}^2$$\n \n**2. Bereken $t_{\\textrm{rem}}$**\n \n De beginsnelheid is 100 km/h. Dit is $\\frac{100}{3.6}$ = 27,8 m/s. Nu kunnen we berekenen hoe lang het duurt voordat de auto stilstaat: $$a=\\frac{\\Delta v}{t} \\rightarrow t_{\\textrm{rem}}=\\frac{v}{a}=\\frac{\\textrm{27,8  m/s}}{\\textrm{3,33  m/s}^2}=\\textrm{8,33  s}$$\n\n**3. Bereken $s_{\\textrm{rem}}$**\nTijdens het remmen begint de auto met een snelheid van 27,8 m/s en eindigt de auto met een snelheid van 0 m/s. Tijdens het remmen is de *gemiddelde* snelheid dus precies de helft van de beginsnelheid: $$v_{\\textrm{gem.}}=\\frac{v_{\\textrm{begin}}-v_{\\textrm{eind}}}{2}=\\frac{\\textrm{27,8 m/s}-\\textrm{0 m/s}}{2}=\\textrm{13,9 m/s}$$ Nu we de remtijd en gemiddelde snelheid weten, kunnen we de remweg berekenen: $$s_{\\textrm{rem}}=v_{\\textrm{gem.}}\\cdot t_{\\textrm{rem}}=\\textrm{13,9 m/s} \\cdot \\textrm{8,33 s}=115.8 = 116 \\textrm{ m}$$",
    "Image": "",
    "Type": "",
    "RTTI": "",
    "Bron": "",
    "Auteur": "",
    "Answers": [
    	{
    		"text": "10 **Newton** uitoefenen $F_z$",
    		"correct": 0,
    		"feedback": "Een **specifieke** kracht, $F$, kan 10 Newton zijn maar dat is niet wat een kracht in het algemeen doet.",
    	},
    	{
    		"text": "De vorm of snelheid van een voorwerp veranderen",
    		"correct": 1,
    		"feedback": "",
    	},
    	{
    		"text": "Aangeven hoe *snel* een voorwerp gaat",
    		"correct": 0,
    		"feedback": "",
    	},
    	{
    		"text": "Aangeven in welke richting een voorwerp beweegt",
    		"correct": 0,
    		"feedback": "De kracht die op een voorwerp werkt kan invloed hebben op de snelheid maar is niet wat een kracht in het algemeen doet",
    	},
    ]
  },
  {
    "Target_ID": 171,
    "Target Label": "Target Label",
    "Target Subdomain": "Target Subdomain",
    "Question_ID": 22222,
    "Question": "Wat is een steukvlak?",
    "Explanation": "Tweede Dummy explanation",
    "Image": "",
    "Type": "",
    "RTTI": "",
    "Bron": "",
    "Auteur": "",
    "Answers": [
    	{
    		"text": "Het vlak waar een voorwerp op rust",
    		"correct": 0,
    		"feedback": "",
    	},
    	{
    		"text": "Het gebied tussen alle punten waar een voorwerp op rust",
    		"correct": 1,
    		"feedback": "",
    	},
    	{
    		"text": "Het gebied waar een voorwerp op moet rusten om niet om te vallen",
    		"correct": 0,
    		"feedback": "",
    	},
    	{
    		"text": "Het grootste oppervlak van een voorwerp",
    		"correct": 0,
    		"feedback": "",
    	},
    ]
  }
 ]

questions_data2 = [
  {
    "Target_ID": 153,
    "Target Label": "Arbeid en kinetische energie",
    "Target Subdomain": "C2",
    "Question_ID": 723,
    "Question": "Een auto van 1200 kg rijdt 100 km/h. Hij remt af met een kracht van 4,00 kN. Bereken de remweg.",
    "Explanation": "Om dit op te lossen, doorloop je de volgende stappen:\n1. Bereken de vertraging van de auto\n2. Gebruik de vertraging om de remtijd te berekenen\n3. Gebruik de remtijd en de gemiddelde snelheid om de remweg te berekenen\n\n**1. Bereken $a_{\\textrm{rem}}$**\n Uit de Tweede wet van Newton ($F_{res}= m\\cdot a$) volgt: $$a = \\frac{F_{res}}{m}=\\frac{4000 \\textrm{ N}}{1200 \\textrm{ kg}}=3.33 \\textrm{ m/s}^2$$\n \n**2. Bereken $t_{\\textrm{rem}}$**\n \n De beginsnelheid is 100 km/h. Dit is $\\frac{100}{3.6}$ = 27,8 m/s. Nu kunnen we berekenen hoe lang het duurt voordat de auto stilstaat: $$a=\\frac{\\Delta v}{t} \\rightarrow t_{\\textrm{rem}}=\\frac{v}{a}=\\frac{\\textrm{27,8  m/s}}{\\textrm{3,33  m/s}^2}=\\textrm{8,33  s}$$\n\n**3. Bereken $s_{\\textrm{rem}}$**\nTijdens het remmen begint de auto met een snelheid van 27,8 m/s en eindigt de auto met een snelheid van 0 m/s. Tijdens het remmen is de *gemiddelde* snelheid dus precies de helft van de beginsnelheid: $$v_{\\textrm{gem.}}=\\frac{v_{\\textrm{begin}}-v_{\\textrm{eind}}}{2}=\\frac{\\textrm{27,8 m/s}-\\textrm{0 m/s}}{2}=\\textrm{13,9 m/s}$$ Nu we de remtijd en gemiddelde snelheid weten, kunnen we de remweg berekenen: $$s_{\\textrm{rem}}=v_{\\textrm{gem.}}\\cdot t_{\\textrm{rem}}=\\textrm{13,9 m/s} \\cdot \\textrm{8,33 s}=115.8 = 116 \\textrm{ m}$$",
    "Image": "",
    "Type": "",
    "RTTI": "",
    "Bron": "",
    "Auteur": "Joachim (Quizziz: H5 NOVA 1e druk ho. 8)",
    "A1": "1500 m",
    "C1": "",
    "F1": "",
    "A2": "116 m",
    "C2": 1,
    "F2": "",
    "A3": "88 m",
    "C3": "",
    "F3": "",
    "A4": "132 m",
    "C4": "",
    "F4": "",
    "A5": "",
    "C5": "",
    "F5": "",
    "A6": "",
    "C6": "",
    "F6": "",
    "": 1,
    "__1": "Done",
    "__2": "26/02/2020 20:39:36",
    "__3": "26-2-2020 20:57:02",
    "__4": "Updated",
    "__5": "Updated"
  },
  {
    "Target_ID": 451,
    "Target Label": "Golfsnelheid formule",
    "Target Subdomain": "B1",
    "Question_ID": 735,
    "Question": "De golfsnelheid is 25 m/s en de golflengte is 5 m. Wat is de trillingstijd?",
    "Explanation": "$T=\\frac{1}{f}$ en $f=\\frac{v_{\\textrm{golf}}}{\\lambda}$ dus $T=\\frac{\\lambda}{v_{\\textrm{golf}}}=\\frac{5 \\textrm{ m}}{25 \\textrm{ m/s}}= \\textrm{0,2 s}$",
    "Image": "",
    "Type": "",
    "RTTI": "",
    "Bron": "",
    "Auteur": "",
    "A1": "5 s",
    "C1": "",
    "F1": "",
    "A2": "125 s",
    "C2": "",
    "F2": "",
    "A3": "0,2 s",
    "C3": 1,
    "F3": "",
    "A4": "20 s",
    "C4": "",
    "F4": "",
    "A5": "",
    "C5": "",
    "F5": "",
    "A6": "",
    "C6": "",
    "F6": "",
    "": 1,
    "__1": "Done",
    "__2": "19/09/2019 15:04:33",
    "__3": "31-1-2020 9:05:00",
    "__4": "Updated",
    "__5": "Updated"
  },
  {
    "Target_ID": 502,
    "Target Label": "Elektrische schakelingen stappenplan",
    "Target Subdomain": "D1",
    "Question_ID": 1704,
    "Question": "Hieronder staan 3 uitspraken over de wetten van Kirchhoff. Welke van deze uitspraken zijn waar?\n- A) De stroomwet geldt voor alle stromen van/naar één bepaald punt in een schakeling.\n- B) In formulevorm luidt de stroomwet $\\sum_{i}I_i=0$ A ($i$=1,2,3…).\n- C) Bij de spanningswet worden batterijen anders behandeld dan weerstanden.",
    "Explanation": "",
    "Image": "",
    "Type": "",
    "RTTI": "",
    "Bron": "NatuurkundeUitgelegd",
    "Auteur": "",
    "A1": "A B C",
    "C1": 1,
    "F1": "",
    "A2": "A B",
    "C2": "",
    "F2": "",
    "A3": "A C",
    "C3": "",
    "F3": "",
    "A4": "A",
    "C4": "",
    "F4": "",
    "A5": "B",
    "C5": "",
    "F5": "",
    "A6": "B C",
    "C6": "",
    "F6": "",
    "": 1,
    "__1": "Done",
    "__2": "13/02/2020 13:48:28",
    "__3": "26-2-2020 20:57:02",
    "__4": "Updated",
    "__5": "Updated"
  }
]